# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Subject.create(name:'理科')
Subject.create(name:'社会')

Field.create!(subject_id:1, field__name:'身近な生物の観察')
Field.create(subject_id:1, field__name:'植物の特徴と分類')
Field.create(subject_id:1, field__name:'動物の特徴と分類')
Field.create(subject_id:1, field__name:'地震')
Field.create(subject_id:1, field__name:'火山')
Field.create(subject_id:1, field__name:'地層')
Field.create(subject_id:1, field__name:'いろいろな物質とその性質')
Field.create(subject_id:1, field__name:'いろいろな気体とその性質')
Field.create(subject_id:1, field__name:'水溶液の性質')
Field.create(subject_id:1, field__name:'物質のすがたとその変化')
Field.create(subject_id:1, field__name:'光')
Field.create(subject_id:1, field__name:'音')
Field.create(subject_id:1, field__name:'力')
Field.create(subject_id:2, field__name:'人類の始まり')
Field.create(subject_id:2, field__name:'縄文時代、弥生時代')

Question.create!(sentence:'手に持った花などのつくりをルーペで観察するとき、ルーペと観察物のどちらを前後に動かして観察するか。', subject_id:1, field_id:1)
Question.create(sentence:'スケッチを描くとき、細い線で描くか、太い線で描くか。', subject_id:1, field_id:1)
Question.create(sentence:'スケッチを描くとき、影をつけて描くか、つけないで描くか。', subject_id:1, field_id:1)
Question.create(sentence:'顕微鏡は、直射日光のあたる場所、当たらない場所のどちらで使うか。', subject_id:1, field_id:1)
Question.create(sentence:'ステージ上下式顕微鏡で観察するとき、最初は対物レンズを一番低倍率にするか、高倍率にするか。', subject_id:1, field_id:1)
Question.create(sentence:'ステージ上下式顕微鏡で観察するときに、スライドガラスに試料をのせてカバーガラスをかけたものを何というか。', subject_id:1, field_id:1)
Question.create(sentence:'ステージ上下式顕微鏡で観察するとき、まずプレパラートと対物レンズは近づけておくか、遠ざけておくか。', subject_id:1, field_id:1)
Question.create(sentence:'接眼レンズが10×、対物レンズが20のとき、顕微鏡の倍率は何倍か。', subject_id:1, field_id:1)
Question.create(sentence:'生物の分類では、共通点を持つものは同じグループ、違うグループのどちらにまとめるか。', subject_id:1, field_id:1)
Question.create(sentence:'花弁、おしべ、めしべ、がくのうち、最も内側にあるつくりは何か。', subject_id:1, field_id:2)
Question.create(sentence:'花のつくりで、めしべの先端の部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'花のつくりで、めしべのもとのふくらんだ部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'花のつくりで、おしべの先端の部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'花のつくりで受粉後、種子になる部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'受粉後、子房は何になるか。', subject_id:1, field_id:2)
Question.create(sentence:'種子をつくって仲間を増やす植物を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'マツの雄花のりん片で、花粉が入っている部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'マツの雌花のりん片についている受粉後種子になる部分を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'子房がなく胚珠がむき出しになっている植物を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'胚珠が子房の中にある植物を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'葉の表面に見られるすじを何というか。', subject_id:1, field_id:2)
Question.create(sentence:'被子植物のうち、子葉が1枚の植物を何というか。', subject_id:1, field_id:2)
Question.create(sentence:'被子植物のうち、子葉が2枚のものを何というか。', subject_id:1, field_id:2)

Choice.create(choice_no:1, choice:'ルーペ', answer:'false', question_id:1)
Choice.create(choice_no:2, choice:'観察物', answer:'true', question_id:1)
Choice.create(choice_no:1, choice:'細い線', answer:'true', question_id:2)
Choice.create(choice_no:2, choice:'太い線', answer:'false', question_id:2)
Choice.create(choice_no:1, choice:'つけて描く', answer:'false', question_id:3)
Choice.create(choice_no:2, choice:'つけないで描く', answer:'true', question_id:3)
Choice.create(choice_no:1, choice:'当たる場所', answer:'false', question_id:4)
Choice.create(choice_no:2, choice:'当たらない場所', answer:'true', question_id:4)
Choice.create(choice_no:1, choice:'低倍率', answer:'true', question_id:5)
Choice.create(choice_no:2, choice:'高倍率', answer:'false', question_id:5)
Choice.create(choice_no:1, choice:'パラプレート', answer:'false', question_id:6)
Choice.create(choice_no:2, choice:'プレートガラス', answer:'false', question_id:6)
Choice.create(choice_no:3, choice:'プレパラート', answer:'true', question_id:6)
Choice.create(choice_no:4, choice:'ステージガラス', answer:'false', question_id:6)
Choice.create(choice_no:1, choice:'近づけておく', answer:'true', question_id:7)
Choice.create(choice_no:2, choice:'遠ざけておく', answer:'false', question_id:7)
Choice.create(choice_no:1, choice:'10倍', answer:'false', question_id:8)
Choice.create(choice_no:2, choice:'20倍', answer:'false', question_id:8)
Choice.create(choice_no:3, choice:'200倍', answer:'true', question_id:8)
Choice.create(choice_no:4, choice:'2000倍', answer:'false', question_id:8)
Choice.create(choice_no:1, choice:'同じグループ', answer:'true', question_id:9)
Choice.create(choice_no:2, choice:'違うグループ', answer:'false', question_id:9)

